initial pass at install | lint | format | it
elastic/rally-tracks pull request #198
Opened 2021-08-30 19:37 UTC by DJRickyB

With this commit we add barebones functionality for managing rally-tracks as a single project, with capabilities pre-requisite for Continuous Integration.  Specifically, we add a Makefile, with targets and configurations for:
* install
* lint
* format
* it
Note that the code does not currently pass this lightweight configuration, and changes meant to re-format or clean up the code will happen in a later PR.

2021-08-31 02:34 UTC, b-deam reviewed
I gave it a quick test and it works (except for `pytest` missing).

2021-08-31 02:34 UTC, b-deam commented on Makefile
> +	. $(VENV_ACTIVATE_FILE); pytest tests/
Do we also want to add pytest to `requirements.txt`?

2021-09-08 00:41 UTC, ebadyano commented on Makefile
> +venv-create:
Do we want venv-create to be executed as part of make install, similarly to rally Makefile?

2021-11-08 17:58 UTC, DJRickyB commented on .pylintrc
> +[MASTER]
this file is the default generated from `pylint --generate-rcfile >.pylintrc`.  no special rules here as opposed to the Rally one.  As noted in the PR description, this repo actually fails linting currently so modifications to the ruleset as well as code cleanup will happen in a follow-up PR.

2021-11-08 18:02 UTC, DJRickyB commented
This is re-ready for re-review :)

New approach is lighterweight and does not dictate its own separately-maintained Python or library versions for the (eventual) integration testing.  Please let me know what you think of the submodule thing here

2021-11-09 07:12 UTC, pquentin requested changes
I sympathize with your willingness to make progress, any progress, as the current situation is dire, but I'm worried that this goes into the wrong direction.

Using a git submodule is a hack and make(1) just feels like the wrong tool here, and we keep running into its limitations. If only we had a good cross-platform programming language well-suited to writing scripts, and a good way to import code from other repositories!

I'm joking: we do have that. We could install Rally with pip (even from git if we wanted too), add any shared code in esrally/testing.py and use nox to run lint and tests, dropping tox. I'm not sure how we should handle the virtual environment creation yet, as it's outside of nox's scope. There are many concerns here, which is why we should probably resume the offline discussion we had around testing this repository. It seems to me that we now have enough information about CI limitations to do that. cc @michaelbaamonde

2021-11-09 13:42 UTC, DJRickyB commented on Makefile
> +	cd rally && make install
Philosophically, this is all CI machinery, for use in an ephemeral environment such as a Jenkins or GH Actions worker. Doesn't mean there's not a better way to do this but I wanted to point that out from the intent

2021-11-09 13:42 UTC, DJRickyB commented on Makefile
> +VENV_ACTIVATE = . $(VENV_ACTIVATE)
yep!

2021-11-09 13:43 UTC, DJRickyB commented on Makefile
> +export TRACK_DIRS = $(shell find -E . -regex ".*/track\.json"|sed -r 's|/[^/]+$$||' | sort -u)
yeah... why did i do that?

2021-11-09 13:49 UTC, DJRickyB commented
Thanks @pquentin! I added you here for a reason :)

> Using a git submodule is a hack and make(1) just feels like the wrong tool here, and we keep running into its limitations. If only we had a good cross-platform programming language well-suited to writing scripts, and a good way to import code from other repositories!

The submodule bit was to consider matching compatible rally-tracks branches with compatible Rally versions, using the ref mechanism in non-main branches to ensure compatibility where we expected it, bi-directionally.  I think this can probably be done just as well with Pip, as you mention, but as I wanted to also source venv creation and compatible Python/dev dependencies, the submodule quickly became an all-in-one solution.
 
I think the hack can live here, maybe even justifiably, with an established entry point which from the CI machine's perspective wouldn't change even as we improve or re-factor under-the-hood.  So my immediate task will be to write a top-level CI script, but I'd be curious about your thoughts on the above set of goals and intentions before I go any further with the implementation detail

2021-11-15 10:31 UTC, pquentin commented on Makefile
> +	cd rally && make install
I see what you mean. But we'll also use this machinery, so it makes sense to optimize for us. If things are barely usable in .ci/build.sh, I don't really mind, but in tools we use such as the Makefile I think good UX is important.

2021-11-15 10:31 UTC, pquentin commented
The arguments for the submodule are solid, thanks.

@michaelbaamonde Should we close this for now?

2021-12-09 13:44 UTC, closed without merging