fix: disallow usage of ilm lifecycle for serverless
elastic/rally-tracks pull request #647
Opened 2024-08-29 18:02 UTC by salvatore-campagna

Serverless deployments miss ILM. As a result component templates should not use the lifecycle setting. Here we introduce a setting which allows us to exclude the lifecycle setting either using `lifecycle` parameter or a `build_flavor` parameter. This mimics what we do already for the elastic/logs track.

This needs backport to 8.15 branch.

2024-08-29 18:10 UTC, salvatore-campagna commented
@gareth-ellis @inqueue I don't see what is wrong here...any help?

2024-08-29 23:32 UTC, inqueue commented
> @gareth-ellis @inqueue I don't see what is wrong here...any help?

It seems to not like a misplaced `%` somewhere. I didn't see anything in your changes with a brief look. I should be able to take a closer look on Friday if it is still broken.

2024-08-30 07:39 UTC, gareth-ellis requested changes
The tests are failing due to syntax issues - we can see in the output its esrally list tracks - you don't get too much more helpful info, but it points in the right direction

if you run you get.... 
```
gareth@Gareths-MBP rally-tracks % esrally list tracks --track-path elastic/security

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[ERROR] Cannot list. unexpected '%'.

Getting further help:
*********************
* Check the log files in /Users/gareth/.rally/logs for errors.
* Read the documentation at https://esrally.readthedocs.io/en/2.11.0/.
* Ask a question on the forum at https://discuss.elastic.co/tags/c/elastic-stack/elasticsearch/rally.
* Raise an issue at https://github.com/elastic/rally/issues and include the log files in /Users/gareth/.rally/logs.
```
And then reviewing the log suggests the file to look at...
```
2024-08-30 07:33:51,838 -not-actor-/PID:93122 esrally.track.loader INFO Loading template [definition for component template logs-endpoint.events.library@package in /Users/gareth/repos/rally-tracks/elastic/security/./templates/component/logs-endpoint.events.library@package.json].
2024-08-30 07:33:51,838 -not-actor-/PID:93122 esrally.track.loader ERROR Cannot load track [security]
Traceback (most recent call last):
```
the error is coming from that the double curly brackets are typically for variable substitution and % is an illegal character there

2024-08-30 07:39 UTC, gareth-ellis commented on elastic/security/templates/component/logs-endpoint.events.library@package.json
> +          {{% if lifecycle == "ilm" or (not lifecycle and build_flavor == "default") %}
double curly brackets
```suggestion
          {% if lifecycle == "ilm" or (not lifecycle and build_flavor == "default") %}
```

2024-08-30 07:39 UTC, gareth-ellis commented on elastic/security/templates/component/logs-endpoint.events.library@settings.json
> +        {{% if lifecycle == "ilm" or (not lifecycle and build_flavor == "default") %}
here as well
```suggestion
        {% if lifecycle == "ilm" or (not lifecycle and build_flavor == "default") %}
```

2024-08-30 08:07 UTC, salvatore-campagna commented on elastic/security/templates/component/logs-endpoint.events.library@package.json
> +          {{% if lifecycle == "ilm" or (not lifecycle and build_flavor == "default") %}
👍  Thanks Gareth...

2024-08-30 08:11 UTC, gareth-ellis approved these changes
LGTM

2024-08-30 11:47 UTC, merged